/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fileserver_constants.h"



const fileserverConstants g_fileserver_constants;

fileserverConstants::fileserverConstants() {
}



