/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fileserver_CONSTANTS_H
#define fileserver_CONSTANTS_H

#include "fileserver_types.h"



class fileserverConstants {
 public:
  fileserverConstants();

};

extern const fileserverConstants g_fileserver_constants;



#endif
